// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-study/src/proto/senior/senior.proto

package proto_senior

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	quick_start "go-study/protock_start"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// HelloResponse 响应结构
type HelloResponse struct {
	People               *quick_start.Person `protobuf:"bytes,1,opt,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb75077d47e2265, []int{0}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetPeople() *quick_start.Person {
	if m != nil {
		return m.People
	}
	return nil
}

// HelloRequest 请求结构
type HelloRequest struct {
	People               *quick_start.Person `protobuf:"bytes,1,opt,name=people,proto3" json:"people,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_deb75077d47e2265, []int{1}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetPeople() *quick_start.Person {
	if m != nil {
		return m.People
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloResponse)(nil), "proto.senior.HelloResponse")
	proto.RegisterType((*HelloRequest)(nil), "proto.senior.HelloRequest")
}

func init() {
	proto.RegisterFile("go-study/src/proto/senior/senior.proto", fileDescriptor_deb75077d47e2265)
}

var fileDescriptor_deb75077d47e2265 = []byte{
	// 183 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4b, 0xcf, 0xd7, 0x2d,
	0x2e, 0x29, 0x4d, 0xa9, 0xd4, 0x2f, 0x2e, 0x4a, 0xd6, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f,
	0x4e, 0xcd, 0xcb, 0xcc, 0x2f, 0x82, 0x52, 0x7a, 0x60, 0x31, 0x21, 0x1e, 0x30, 0xa5, 0x07, 0x11,
	0x93, 0xd2, 0xc6, 0xa2, 0xab, 0xb0, 0x34, 0x33, 0x39, 0x3b, 0xbe, 0xb8, 0x24, 0xb1, 0xa8, 0x44,
	0xbf, 0x20, 0xb5, 0xa8, 0x38, 0x3f, 0x0f, 0xa2, 0x55, 0xc9, 0x89, 0x8b, 0xd7, 0x23, 0x35, 0x27,
	0x27, 0x3f, 0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0xc8, 0x90, 0x8b, 0xad, 0x20, 0x35,
	0xbf, 0x20, 0x27, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x12, 0xa2, 0x50, 0x0f, 0xc9,
	0x04, 0xbd, 0x00, 0xb0, 0x09, 0x41, 0x50, 0x85, 0x4a, 0x8e, 0x5c, 0x3c, 0x50, 0x33, 0x0a, 0x4b,
	0x53, 0x8b, 0x4b, 0xc8, 0x30, 0xc2, 0xc8, 0x8f, 0x8b, 0x15, 0x6c, 0x84, 0x90, 0x2b, 0x17, 0x47,
	0x70, 0x62, 0x25, 0x84, 0x2d, 0xa5, 0x87, 0xec, 0x2f, 0x3d, 0x64, 0x3b, 0xa4, 0xa4, 0xb1, 0xca,
	0x41, 0xfc, 0xa0, 0xc4, 0x90, 0xc4, 0x06, 0x96, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0x28, 0x66, 0xac, 0x42, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	// 定义SayHello方法
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/proto.senior.Hello/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	// 定义SayHello方法
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

// UnimplementedHelloServer can be embedded to have forward compatible implementations.
type UnimplementedHelloServer struct {
}

func (*UnimplementedHelloServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.senior.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.senior.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-study/src/proto/senior/senior.proto",
}
